### PR TITLE
Added Crazy For You by Madonna

### PR DESCRIPTION
**Pull request by cecilevdwaal**
https://open.spotify.com/track/6B4oVElDIKRNcNUary0WG7?si=uOZqfHQ8QVybZc3Kdzx_8w

### CODE REVIEW

**Comment by rvanlaarhoven** [comment]
Need to get used to this one. It's somehow a bit uptempo, but also not really :)

**Comment by rvanlaarhoven** [comment]
I had shuffle on and this one played next; https://open.spotify.com/track/7izFzcBTx3DVXFeFYDeZKB

**Comment by cecilevdwaal** [comment]
Haha nice! I was watching a series and there was a couple slow-dancing on an 80s prom to this song 👯‍♂️  Plus Madonna wasn't in the list yet!

**Comment by cecilevdwaal** [comment]
Finally found the episode where the couple was slow-dancing! Check out 'Glow' on Netflix, season 2 episode 9 at minute 23. https://www.netflix.com/watch/80226271

**Comment by rvanlaarhoven** [comment]
Still think the Crazy for you is a bit too fast. Updated the pull request with `Take a Bow`, but while listening to it, it just feels a bit too boring

**Comment by rvanlaarhoven** [comment]
I'm closing this as won't fix.

**Pull request closed without merging**
